language: php

env:
  global:
    - TASK_TESTS_COVERAGE=0
    - USE_LOWEST_DEPENDENCIES=0

matrix:
  fast_finish: true
  include:
    - php: 5.6

    - php: 7.0

    - php: 7.1

    - php: 7.2
    
  allow_failures:
    - php: 7.2

install:
  # show versions and env information
  - php --version
  - composer --version
  - pg_config --version

  # Install dependencies
  - travis_retry composer self-update
  - if [ $USE_LOWEST_DEPENDENCIES == 0 ]; then composer install --no-interaction; fi;
  - if [ $USE_LOWEST_DEPENDENCIES == 1 ]; then composer update --prefer-lowest --no-interaction; fi;
  - composer dumpautoload -o

script:
  - vendor/bin/phpunit --verbose
